/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AllocationStatusEnum } from './AllocationStatusEnum';
import {
    AllocationStatusEnumFromJSON,
    AllocationStatusEnumFromJSONTyped,
    AllocationStatusEnumToJSON,
    AllocationStatusEnumToJSONTyped,
} from './AllocationStatusEnum';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
    EmbeddedModelSchemaToJSONTyped,
} from './EmbeddedModelSchema';

/**
 * This is one of the 3 possible urls that will route to your cloud :).
 * @export
 * @interface AllocationCloudUrl
 */
export interface AllocationCloudUrl {
    /**
     * 
     * @type {EmbeddedModelSchema}
     * @memberof AllocationCloudUrl
     */
    schema?: EmbeddedModelSchema;
    /**
     * 
     * @type {AllocationStatusEnum}
     * @memberof AllocationCloudUrl
     */
    status: AllocationStatusEnum;
    /**
     * this is the base url that is used to communicat with your vpc.
     * @type {string}
     * @memberof AllocationCloudUrl
     */
    url: string;
}


/**
 * Check if a given object implements the AllocationCloudUrl interface.
 */
export function instanceOfAllocationCloudUrl(value: object): value is AllocationCloudUrl {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function AllocationCloudUrlFromJSON(json: any): AllocationCloudUrl {
    return AllocationCloudUrlFromJSONTyped(json, false);
}

export function AllocationCloudUrlFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllocationCloudUrl {
    if (json == null) {
        return json;
    }
    return {
        
        'schema': json['schema'] == null ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'status': AllocationStatusEnumFromJSON(json['status']),
        'url': json['url'],
    };
}

export function AllocationCloudUrlToJSON(json: any): AllocationCloudUrl {
    return AllocationCloudUrlToJSONTyped(json, false);
}

export function AllocationCloudUrlToJSONTyped(value?: AllocationCloudUrl | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schema': EmbeddedModelSchemaToJSON(value['schema']),
        'status': AllocationStatusEnumToJSON(value['status']),
        'url': value['url'],
    };
}

