/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Score } from './Score';
import {
    ScoreFromJSON,
    ScoreFromJSONTyped,
    ScoreToJSON,
} from './Score';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { Annotation } from './Annotation';
import {
    AnnotationFromJSON,
    AnnotationFromJSONTyped,
    AnnotationToJSON,
} from './Annotation';

/**
 * This is the plural of Annotation
 * @export
 * @interface Annotations
 */
export interface Annotations {
    /**
     * 
     * @type {EmbeddedModelSchema}
     * @memberof Annotations
     */
    schema?: EmbeddedModelSchema;
    /**
     * 
     * @type {Array<Annotation>}
     * @memberof Annotations
     */
    iterable: Array<Annotation>;
    /**
     * This is a Map<String, int> where the the key is an annotation id.
     * @type {{ [key: string]: number; }}
     * @memberof Annotations
     */
    indices?: { [key: string]: number; };
    /**
     * 
     * @type {Score}
     * @memberof Annotations
     */
    score?: Score;
}

/**
 * Check if a given object implements the Annotations interface.
 */
export function instanceOfAnnotations(value: object): value is Annotations {
    if (!('iterable' in value) || value['iterable'] === undefined) return false;
    return true;
}

export function AnnotationsFromJSON(json: any): Annotations {
    return AnnotationsFromJSONTyped(json, false);
}

export function AnnotationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Annotations {
    if (json == null) {
        return json;
    }
    return {
        
        'schema': json['schema'] == null ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'iterable': ((json['iterable'] as Array<any>).map(AnnotationFromJSON)),
        'indices': json['indices'] == null ? undefined : json['indices'],
        'score': json['score'] == null ? undefined : ScoreFromJSON(json['score']),
    };
}

export function AnnotationsToJSON(value?: Annotations | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'schema': EmbeddedModelSchemaToJSON(value['schema']),
        'iterable': ((value['iterable'] as Array<any>).map(AnnotationToJSON)),
        'indices': value['indices'],
        'score': ScoreToJSON(value['score']),
    };
}

