/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmbeddedModelSchema,
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
    ReferencedAnnotation,
    ReferencedAnnotationFromJSON,
    ReferencedAnnotationFromJSONTyped,
    ReferencedAnnotationToJSON,
    ReferencedConversation,
    ReferencedConversationFromJSON,
    ReferencedConversationFromJSONTyped,
    ReferencedConversationToJSON,
} from './index';

/**
 * This is the output model for "/conversation/{conversation}/summarize
 * @export
 * @interface ConversationSummarizeOutput
 */
export interface ConversationSummarizeOutput {
    /**
     * 
     * @type {EmbeddedModelSchema}
     * @memberof ConversationSummarizeOutput
     */
    schema?: EmbeddedModelSchema;
    /**
     * 
     * @type {ReferencedConversation}
     * @memberof ConversationSummarizeOutput
     */
    conversation: ReferencedConversation;
    /**
     * 
     * @type {ReferencedAnnotation}
     * @memberof ConversationSummarizeOutput
     */
    annotation: ReferencedAnnotation;
}

export function ConversationSummarizeOutputFromJSON(json: any): ConversationSummarizeOutput {
    return ConversationSummarizeOutputFromJSONTyped(json, false);
}

export function ConversationSummarizeOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationSummarizeOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'conversation': ReferencedConversationFromJSON(json['conversation']),
        'annotation': ReferencedAnnotationFromJSON(json['annotation']),
    };
}

export function ConversationSummarizeOutputToJSON(value?: ConversationSummarizeOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'conversation': ReferencedConversationToJSON(value.conversation),
        'annotation': ReferencedAnnotationToJSON(value.annotation),
    };
}


