/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Distribution,
    DistributionFromJSON,
    DistributionFromJSONTyped,
    DistributionToJSON,
    EmbeddedModelSchema,
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './index';

/**
 * This is the plural Model of a Distribution.
 * @export
 * @interface Distributions
 */
export interface Distributions {
    /**
     * 
     * @type {Array<Distribution>}
     * @memberof Distributions
     */
    iterable: Array<Distribution>;
    /**
     * 
     * @type {EmbeddedModelSchema}
     * @memberof Distributions
     */
    schema?: EmbeddedModelSchema;
}

export function DistributionsFromJSON(json: any): Distributions {
    return DistributionsFromJSONTyped(json, false);
}

export function DistributionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Distributions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'iterable': ((json['iterable'] as Array<any>).map(DistributionFromJSON)),
        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
    };
}

export function DistributionsToJSON(value?: Distributions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'iterable': ((value.iterable as Array<any>).map(DistributionToJSON)),
        'schema': EmbeddedModelSchemaToJSON(value.schema),
    };
}


