/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * TODO
 * @export
 */
export const EmbeddingsSearchOptionsEmbeddingTypeEnum = {
    Jina: 'JINA',
    Ncs: 'NCS'
} as const;
export type EmbeddingsSearchOptionsEmbeddingTypeEnum = typeof EmbeddingsSearchOptionsEmbeddingTypeEnum[keyof typeof EmbeddingsSearchOptionsEmbeddingTypeEnum];


export function instanceOfEmbeddingsSearchOptionsEmbeddingTypeEnum(value: any): boolean {
    for (const key in EmbeddingsSearchOptionsEmbeddingTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(EmbeddingsSearchOptionsEmbeddingTypeEnum, key)) {
            if (EmbeddingsSearchOptionsEmbeddingTypeEnum[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EmbeddingsSearchOptionsEmbeddingTypeEnumFromJSON(json: any): EmbeddingsSearchOptionsEmbeddingTypeEnum {
    return EmbeddingsSearchOptionsEmbeddingTypeEnumFromJSONTyped(json, false);
}

export function EmbeddingsSearchOptionsEmbeddingTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddingsSearchOptionsEmbeddingTypeEnum {
    return json as EmbeddingsSearchOptionsEmbeddingTypeEnum;
}

export function EmbeddingsSearchOptionsEmbeddingTypeEnumToJSON(value?: EmbeddingsSearchOptionsEmbeddingTypeEnum | null): any {
    return value as any;
}

