/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { ReferencedActivity } from './ReferencedActivity';
import {
    ReferencedActivityFromJSON,
    ReferencedActivityFromJSONTyped,
    ReferencedActivityToJSON,
} from './ReferencedActivity';

/**
 * 
 * @export
 * @interface FlattenedActivities
 */
export interface FlattenedActivities {
    /**
     * 
     * @type {EmbeddedModelSchema}
     * @memberof FlattenedActivities
     */
    schema?: EmbeddedModelSchema;
    /**
     * 
     * @type {Array<ReferencedActivity>}
     * @memberof FlattenedActivities
     */
    iterable: Array<ReferencedActivity>;
}

/**
 * Check if a given object implements the FlattenedActivities interface.
 */
export function instanceOfFlattenedActivities(value: object): boolean {
    if (!('iterable' in value)) return false;
    return true;
}

export function FlattenedActivitiesFromJSON(json: any): FlattenedActivities {
    return FlattenedActivitiesFromJSONTyped(json, false);
}

export function FlattenedActivitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlattenedActivities {
    if (json == null) {
        return json;
    }
    return {
        
        'schema': json['schema'] == null ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'iterable': ((json['iterable'] as Array<any>).map(ReferencedActivityFromJSON)),
    };
}

export function FlattenedActivitiesToJSON(value?: FlattenedActivities | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'schema': EmbeddedModelSchemaToJSON(value['schema']),
        'iterable': ((value['iterable'] as Array<any>).map(ReferencedActivityToJSON)),
    };
}

