/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Classification } from './Classification';
import {
    ClassificationFromJSON,
    ClassificationFromJSONTyped,
    ClassificationToJSON,
} from './Classification';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { LanguageServerProtocolLocation } from './LanguageServerProtocolLocation';
import {
    LanguageServerProtocolLocationFromJSON,
    LanguageServerProtocolLocationFromJSONTyped,
    LanguageServerProtocolLocationToJSON,
} from './LanguageServerProtocolLocation';
import type { TransferableString } from './TransferableString';
import {
    TransferableStringFromJSON,
    TransferableStringFromJSONTyped,
    TransferableStringToJSON,
} from './TransferableString';

/**
 * This is a given bit of text/code that is selected in the IDE, this can be a copy/paste/selection
 * 
 * location: this is the given location provided by the LSP(might need to be a different object we will see)
 * @export
 * @interface IDESelection
 */
export interface IDESelection {
    /**
     * 
     * @type {EmbeddedModelSchema}
     * @memberof IDESelection
     */
    schema?: EmbeddedModelSchema;
    /**
     * 
     * @type {LanguageServerProtocolLocation}
     * @memberof IDESelection
     */
    location?: LanguageServerProtocolLocation;
    /**
     * 
     * @type {Classification}
     * @memberof IDESelection
     */
    classification?: Classification;
    /**
     * 
     * @type {TransferableString}
     * @memberof IDESelection
     */
    value?: TransferableString;
}

/**
 * Check if a given object implements the IDESelection interface.
 */
export function instanceOfIDESelection(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IDESelectionFromJSON(json: any): IDESelection {
    return IDESelectionFromJSONTyped(json, false);
}

export function IDESelectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): IDESelection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'location': !exists(json, 'location') ? undefined : LanguageServerProtocolLocationFromJSON(json['location']),
        'classification': !exists(json, 'classification') ? undefined : ClassificationFromJSON(json['classification']),
        'value': !exists(json, 'value') ? undefined : TransferableStringFromJSON(json['value']),
    };
}

export function IDESelectionToJSON(value?: IDESelection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'location': LanguageServerProtocolLocationToJSON(value.location),
        'classification': ClassificationToJSON(value.classification),
        'value': TransferableStringToJSON(value.value),
    };
}

