/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
    EmbeddedModelSchemaToJSONTyped,
} from './EmbeddedModelSchema';
import type { LanguageServerProtocolLocationRangePosition } from './LanguageServerProtocolLocationRangePosition';
import {
    LanguageServerProtocolLocationRangePositionFromJSON,
    LanguageServerProtocolLocationRangePositionFromJSONTyped,
    LanguageServerProtocolLocationRangePositionToJSON,
    LanguageServerProtocolLocationRangePositionToJSONTyped,
} from './LanguageServerProtocolLocationRangePosition';

/**
 * modeled after this (https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#range)
 * @export
 * @interface LanguageServerProtocolLocationRange
 */
export interface LanguageServerProtocolLocationRange {
    /**
     * 
     * @type {EmbeddedModelSchema}
     * @memberof LanguageServerProtocolLocationRange
     */
    schema?: EmbeddedModelSchema;
    /**
     * 
     * @type {LanguageServerProtocolLocationRangePosition}
     * @memberof LanguageServerProtocolLocationRange
     */
    start: LanguageServerProtocolLocationRangePosition;
    /**
     * 
     * @type {LanguageServerProtocolLocationRangePosition}
     * @memberof LanguageServerProtocolLocationRange
     */
    end: LanguageServerProtocolLocationRangePosition;
}


/**
 * Check if a given object implements the LanguageServerProtocolLocationRange interface.
 */
export function instanceOfLanguageServerProtocolLocationRange(value: object): value is LanguageServerProtocolLocationRange {
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    return true;
}

export function LanguageServerProtocolLocationRangeFromJSON(json: any): LanguageServerProtocolLocationRange {
    return LanguageServerProtocolLocationRangeFromJSONTyped(json, false);
}

export function LanguageServerProtocolLocationRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LanguageServerProtocolLocationRange {
    if (json == null) {
        return json;
    }
    return {
        
        'schema': json['schema'] == null ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'start': LanguageServerProtocolLocationRangePositionFromJSON(json['start']),
        'end': LanguageServerProtocolLocationRangePositionFromJSON(json['end']),
    };
}

export function LanguageServerProtocolLocationRangeToJSON(json: any): LanguageServerProtocolLocationRange {
    return LanguageServerProtocolLocationRangeToJSONTyped(json, false);
}

export function LanguageServerProtocolLocationRangeToJSONTyped(value?: LanguageServerProtocolLocationRange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schema': EmbeddedModelSchemaToJSON(value['schema']),
        'start': LanguageServerProtocolLocationRangePositionToJSON(value['start']),
        'end': LanguageServerProtocolLocationRangePositionToJSON(value['end']),
    };
}

