/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * This describes the type of a node ie an asset, tag, website, format... ETC
 * @export
 * @enum {string}
 */
export enum NodeTypeEnum {
    Tag = 'TAG',
    Website = 'WEBSITE',
    Format = 'FORMAT',
    Asset = 'ASSET'
}

export function NodeTypeEnumFromJSON(json: any): NodeTypeEnum {
    return NodeTypeEnumFromJSONTyped(json, false);
}

export function NodeTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeTypeEnum {
    return json as NodeTypeEnum;
}

export function NodeTypeEnumToJSON(value?: NodeTypeEnum | null): any {
    return value as any;
}

