/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enum used for the status of Ollama
 * @export
 */
export const OllamaDeploymentStatusEnum = {
    Unknown: 'UNKNOWN',
    Initialized: 'INITIALIZED',
    InProgress: 'IN-PROGRESS',
    Completed: 'COMPLETED',
    Failed: 'FAILED',
    Canceled: 'CANCELED',
    Reset: 'RESET'
} as const;
export type OllamaDeploymentStatusEnum = typeof OllamaDeploymentStatusEnum[keyof typeof OllamaDeploymentStatusEnum];


export function instanceOfOllamaDeploymentStatusEnum(value: any): boolean {
    for (const key in OllamaDeploymentStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(OllamaDeploymentStatusEnum, key)) {
            if (OllamaDeploymentStatusEnum[key as keyof typeof OllamaDeploymentStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OllamaDeploymentStatusEnumFromJSON(json: any): OllamaDeploymentStatusEnum {
    return OllamaDeploymentStatusEnumFromJSONTyped(json, false);
}

export function OllamaDeploymentStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): OllamaDeploymentStatusEnum {
    return json as OllamaDeploymentStatusEnum;
}

export function OllamaDeploymentStatusEnumToJSON(value?: OllamaDeploymentStatusEnum | null): any {
    return value as any;
}

export function OllamaDeploymentStatusEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): OllamaDeploymentStatusEnum {
    return value as OllamaDeploymentStatusEnum;
}

