/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmbeddedModelSchema,
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
    RelevantQGPTSeed,
    RelevantQGPTSeedFromJSON,
    RelevantQGPTSeedFromJSONTyped,
    RelevantQGPTSeedToJSON,
} from './';

/**
 * This is a plural of RelevantQGPTSeed.
 * @export
 * @interface RelevantQGPTSeeds
 */
export interface RelevantQGPTSeeds {
    /**
     * 
     * @type {EmbeddedModelSchema}
     * @memberof RelevantQGPTSeeds
     */
    schema?: EmbeddedModelSchema;
    /**
     * 
     * @type {Array<RelevantQGPTSeed>}
     * @memberof RelevantQGPTSeeds
     */
    iterable: Array<RelevantQGPTSeed>;
}

export function RelevantQGPTSeedsFromJSON(json: any): RelevantQGPTSeeds {
    return RelevantQGPTSeedsFromJSONTyped(json, false);
}

export function RelevantQGPTSeedsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelevantQGPTSeeds {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'iterable': ((json['iterable'] as Array<any>).map(RelevantQGPTSeedFromJSON)),
    };
}

export function RelevantQGPTSeedsToJSON(value?: RelevantQGPTSeeds | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'iterable': ((value.iterable as Array<any>).map(RelevantQGPTSeedToJSON)),
    };
}


