/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchedWorkstreamPatternEngineVisionEvent } from './SearchedWorkstreamPatternEngineVisionEvent';
import {
    SearchedWorkstreamPatternEngineVisionEventFromJSON,
    SearchedWorkstreamPatternEngineVisionEventFromJSONTyped,
    SearchedWorkstreamPatternEngineVisionEventToJSON,
} from './SearchedWorkstreamPatternEngineVisionEvent';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';

/**
 * This will return a list of the returned events.
 * @export
 * @interface SearchedWorkstreamPatternEngineVisionEvents
 */
export interface SearchedWorkstreamPatternEngineVisionEvents {
    /**
     * 
     * @type {EmbeddedModelSchema}
     * @memberof SearchedWorkstreamPatternEngineVisionEvents
     */
    schema?: EmbeddedModelSchema;
    /**
     * 
     * @type {Array<SearchedWorkstreamPatternEngineVisionEvent>}
     * @memberof SearchedWorkstreamPatternEngineVisionEvents
     */
    iterable: Array<SearchedWorkstreamPatternEngineVisionEvent>;
}

/**
 * Check if a given object implements the SearchedWorkstreamPatternEngineVisionEvents interface.
 */
export function instanceOfSearchedWorkstreamPatternEngineVisionEvents(value: object): value is SearchedWorkstreamPatternEngineVisionEvents {
    if (!('iterable' in value) || value['iterable'] === undefined) return false;
    return true;
}

export function SearchedWorkstreamPatternEngineVisionEventsFromJSON(json: any): SearchedWorkstreamPatternEngineVisionEvents {
    return SearchedWorkstreamPatternEngineVisionEventsFromJSONTyped(json, false);
}

export function SearchedWorkstreamPatternEngineVisionEventsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchedWorkstreamPatternEngineVisionEvents {
    if (json == null) {
        return json;
    }
    return {
        
        'schema': json['schema'] == null ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'iterable': ((json['iterable'] as Array<any>).map(SearchedWorkstreamPatternEngineVisionEventFromJSON)),
    };
}

export function SearchedWorkstreamPatternEngineVisionEventsToJSON(value?: SearchedWorkstreamPatternEngineVisionEvents | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'schema': EmbeddedModelSchemaToJSON(value['schema']),
        'iterable': ((value['iterable'] as Array<any>).map(SearchedWorkstreamPatternEngineVisionEventToJSON)),
    };
}

