/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './EmbeddedModelSchema';
import type { SearchedConversation } from './SearchedConversation';
import {
    SearchedConversationFromJSON,
    SearchedConversationFromJSONTyped,
    SearchedConversationToJSON,
} from './SearchedConversation';

/**
 * This is the plural Model used to return many SearchedConversation.
 * @export
 * @interface SearchedConversations
 */
export interface SearchedConversations {
    /**
     * 
     * @type {EmbeddedModelSchema}
     * @memberof SearchedConversations
     */
    schema?: EmbeddedModelSchema;
    /**
     * 
     * @type {Array<SearchedConversation>}
     * @memberof SearchedConversations
     */
    iterable: Array<SearchedConversation>;
}

/**
 * Check if a given object implements the SearchedConversations interface.
 */
export function instanceOfSearchedConversations(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "iterable" in value;

    return isInstance;
}

export function SearchedConversationsFromJSON(json: any): SearchedConversations {
    return SearchedConversationsFromJSONTyped(json, false);
}

export function SearchedConversationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchedConversations {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'iterable': ((json['iterable'] as Array<any>).map(SearchedConversationFromJSON)),
    };
}

export function SearchedConversationsToJSON(value?: SearchedConversations | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'iterable': ((value.iterable as Array<any>).map(SearchedConversationToJSON)),
    };
}

