/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Recipients } from './Recipients';
import {
    RecipientsFromJSON,
    RecipientsFromJSONTyped,
    RecipientsToJSON,
    RecipientsToJSONTyped,
} from './Recipients';
import type { EmbeddedModelSchema } from './EmbeddedModelSchema';
import {
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
    EmbeddedModelSchemaToJSONTyped,
} from './EmbeddedModelSchema';

/**
 * This is the minimum information needed to distribute a Piece to a Gist.
 * @export
 * @interface SeededGitHubGistDistribution
 */
export interface SeededGitHubGistDistribution {
    /**
     * 
     * @type {EmbeddedModelSchema}
     * @memberof SeededGitHubGistDistribution
     */
    schema?: EmbeddedModelSchema;
    /**
     * 
     * @type {Recipients}
     * @memberof SeededGitHubGistDistribution
     */
    recipients?: Recipients;
    /**
     * we will default to true
     * @type {boolean}
     * @memberof SeededGitHubGistDistribution
     */
    _public?: boolean;
    /**
     * This is the description of the Gist Distribution
     * @type {string}
     * @memberof SeededGitHubGistDistribution
     */
    description?: string;
    /**
     * This is the name of the gist you will add.
     * @type {string}
     * @memberof SeededGitHubGistDistribution
     */
    name: string;
}

/**
 * Check if a given object implements the SeededGitHubGistDistribution interface.
 */
export function instanceOfSeededGitHubGistDistribution(value: object): value is SeededGitHubGistDistribution {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SeededGitHubGistDistributionFromJSON(json: any): SeededGitHubGistDistribution {
    return SeededGitHubGistDistributionFromJSONTyped(json, false);
}

export function SeededGitHubGistDistributionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeededGitHubGistDistribution {
    if (json == null) {
        return json;
    }
    return {
        
        'schema': json['schema'] == null ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'recipients': json['recipients'] == null ? undefined : RecipientsFromJSON(json['recipients']),
        '_public': json['public'] == null ? undefined : json['public'],
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'],
    };
}

export function SeededGitHubGistDistributionToJSON(json: any): SeededGitHubGistDistribution {
    return SeededGitHubGistDistributionToJSONTyped(json, false);
}

export function SeededGitHubGistDistributionToJSONTyped(value?: SeededGitHubGistDistribution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schema': EmbeddedModelSchemaToJSON(value['schema']),
        'recipients': RecipientsToJSON(value['recipients']),
        'public': value['_public'],
        'description': value['description'],
        'name': value['name'],
    };
}

