/* tslint:disable */
/* eslint-disable */
/**
 * This is an open API that holds specific endpoints as a base for Pieces Context Systems
 * The point of this API is to allow us to organize and Auto Generate Code Specific for Connected Applications - this will allow for stateful context abstraction & less code within the Core Connector
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * This is an enum that will determine if this was sent via copied/pasted events from user actions.
 * @export
 * @enum {string}
 */
export enum AssetEventEnum {
    Copied = 'COPIED',
    Pasted = 'PASTED'
}

export function AssetEventEnumFromJSON(json: any): AssetEventEnum {
    return AssetEventEnumFromJSONTyped(json, false);
}

export function AssetEventEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetEventEnum {
    return json as AssetEventEnum;
}

export function AssetEventEnumToJSON(value?: AssetEventEnum | null): any {
    return value as any;
}

