/* tslint:disable */
/* eslint-disable */
/**
 * This is an open API that holds specific endpoints as a base for Pieces Context Systems
 * The point of this API is to allow us to organize and Auto Generate Code Specific for Connected Applications - this will allow for stateful context abstraction & less code within the Core Connector
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmbeddedModelSchema,
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
    FlattenedConversationMessage,
    FlattenedConversationMessageFromJSON,
    FlattenedConversationMessageFromJSONTyped,
    FlattenedConversationMessageToJSON,
} from './';

/**
 * This is a DAG-Safe Minimal version of a ConversationMessage.
 * @export
 * @interface ReferencedConversationMessage
 */
export interface ReferencedConversationMessage {
    /**
     * 
     * @type {EmbeddedModelSchema}
     * @memberof ReferencedConversationMessage
     */
    schema?: EmbeddedModelSchema;
    /**
     * 
     * @type {string}
     * @memberof ReferencedConversationMessage
     */
    id: string;
    /**
     * 
     * @type {FlattenedConversationMessage}
     * @memberof ReferencedConversationMessage
     */
    reference?: FlattenedConversationMessage;
}

export function ReferencedConversationMessageFromJSON(json: any): ReferencedConversationMessage {
    return ReferencedConversationMessageFromJSONTyped(json, false);
}

export function ReferencedConversationMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferencedConversationMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'id': json['id'],
        'reference': !exists(json, 'reference') ? undefined : FlattenedConversationMessageFromJSON(json['reference']),
    };
}

export function ReferencedConversationMessageToJSON(value?: ReferencedConversationMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'id': value.id,
        'reference': FlattenedConversationMessageToJSON(value.reference),
    };
}


