/* tslint:disable */
/* eslint-disable */
/**
 * This is an open API that holds specific endpoints as a base for Pieces Context Systems
 * The point of this API is to allow us to organize and Auto Generate Code Specific for Connected Applications - this will allow for stateful context abstraction & less code within the Core Connector
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum SearchedMatchEnum {
    Title = 'TITLE',
    Annotation = 'ANNOTATION',
    Hint = 'HINT',
    Content = 'CONTENT',
    Fuzzy = 'FUZZY',
    Multiple = 'MULTIPLE',
    Tags = 'TAGS',
    Websites = 'WEBSITES',
    Persons = 'PERSONS'
}

export function SearchedMatchEnumFromJSON(json: any): SearchedMatchEnum {
    return SearchedMatchEnumFromJSONTyped(json, false);
}

export function SearchedMatchEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchedMatchEnum {
    return json as SearchedMatchEnum;
}

export function SearchedMatchEnumToJSON(value?: SearchedMatchEnum | null): any {
    return value as any;
}

