/* tslint:disable */
/* eslint-disable */
/**
 * This is an open API that holds specific endpoints as a base for Pieces Context Systems
 * The point of this API is to allow us to organize and Auto Generate Code Specific for Connected Applications - this will allow for stateful context abstraction & less code within the Core Connector
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmbeddedModelSchema,
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './';

/**
 * Model for ML big query Data collection.
 * @export
 * @interface TLPCodeFragmentDescriptiveStatistics
 */
export interface TLPCodeFragmentDescriptiveStatistics {
    /**
     * 
     * @type {EmbeddedModelSchema}
     * @memberof TLPCodeFragmentDescriptiveStatistics
     */
    schema?: EmbeddedModelSchema;
    /**
     * 
     * @type {string}
     * @memberof TLPCodeFragmentDescriptiveStatistics
     */
    user: string;
    /**
     * 
     * @type {string}
     * @memberof TLPCodeFragmentDescriptiveStatistics
     */
    os: string;
    /**
     * 
     * @type {string}
     * @memberof TLPCodeFragmentDescriptiveStatistics
     */
    language: string;
    /**
     * 
     * @type {number}
     * @memberof TLPCodeFragmentDescriptiveStatistics
     */
    length: number;
    /**
     * 
     * @type {string}
     * @memberof TLPCodeFragmentDescriptiveStatistics
     */
    ast: string;
    /**
     * 
     * @type {string}
     * @memberof TLPCodeFragmentDescriptiveStatistics
     */
    timestamp: string;
    /**
     * 
     * @type {string}
     * @memberof TLPCodeFragmentDescriptiveStatistics
     */
    asset: string;
    /**
     * this is the application in which this was created from.
     * @type {string}
     * @memberof TLPCodeFragmentDescriptiveStatistics
     */
    context: string;
    /**
     * this is the value of the snippet
     * @type {string}
     * @memberof TLPCodeFragmentDescriptiveStatistics
     */
    snippet: string;
}

export function TLPCodeFragmentDescriptiveStatisticsFromJSON(json: any): TLPCodeFragmentDescriptiveStatistics {
    return TLPCodeFragmentDescriptiveStatisticsFromJSONTyped(json, false);
}

export function TLPCodeFragmentDescriptiveStatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TLPCodeFragmentDescriptiveStatistics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'user': json['user'],
        'os': json['os'],
        'language': json['language'],
        'length': json['length'],
        'ast': json['ast'],
        'timestamp': json['timestamp'],
        'asset': json['asset'],
        'context': json['context'],
        'snippet': json['snippet'],
    };
}

export function TLPCodeFragmentDescriptiveStatisticsToJSON(value?: TLPCodeFragmentDescriptiveStatistics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'user': value.user,
        'os': value.os,
        'language': value.language,
        'length': value.length,
        'ast': value.ast,
        'timestamp': value.timestamp,
        'asset': value.asset,
        'context': value.context,
        'snippet': value.snippet,
    };
}


