"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.LinkifyApi = void 0;
const runtime = __importStar(require("../runtime"));
const models_1 = require("../models");
/**
 *
 */
class LinkifyApi extends runtime.BaseAPI {
    /**
     * /linkify [POST]
     */
    async linkifyRaw(requestParameters) {
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        const response = await this.request({
            path: `/linkify`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: (0, models_1.LinkifyToJSON)(requestParameters.linkify),
        });
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, models_1.SharesFromJSON)(jsonValue));
    }
    /**
     * /linkify [POST]
     */
    async linkify(requestParameters) {
        const response = await this.linkifyRaw(requestParameters);
        return await response.value();
    }
    /**
     * - assumption that you have already backed up the asset\'s that you are sending to this endpoint.(b/c the assets are ids.)
     * /linkify/multiple [POST]
     */
    async linkifyMultipleRaw(requestParameters) {
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        const response = await this.request({
            path: `/linkify/multiple`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: (0, models_1.LinkifyMultipleToJSON)(requestParameters.linkifyMultiple),
        });
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, models_1.SharesFromJSON)(jsonValue));
    }
    /**
     * - assumption that you have already backed up the asset\'s that you are sending to this endpoint.(b/c the assets are ids.)
     * /linkify/multiple [POST]
     */
    async linkifyMultiple(requestParameters) {
        const response = await this.linkifyMultipleRaw(requestParameters);
        return await response.value();
    }
    /**
     * This will revoke a link.
     * [POST} /linkify/{share}/revoke
     */
    async linkifyShareRevokeRaw(requestParameters) {
        if (requestParameters.share === null || requestParameters.share === undefined) {
            throw new runtime.RequiredError('share', 'Required parameter requestParameters.share was null or undefined when calling linkifyShareRevoke.');
        }
        const queryParameters = {};
        const headerParameters = {};
        const response = await this.request({
            path: `/linkify/{share}/revoke`.replace(`{${"share"}}`, encodeURIComponent(String(requestParameters.share))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });
        return new runtime.TextApiResponse(response);
    }
    /**
     * This will revoke a link.
     * [POST} /linkify/{share}/revoke
     */
    async linkifyShareRevoke(requestParameters) {
        const response = await this.linkifyShareRevokeRaw(requestParameters);
        return await response.value();
    }
}
exports.LinkifyApi = LinkifyApi;
