name: Release

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ "18.x" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          npm ci

      - name: Show dependencies
        run: npm list

      - name: Extract version from tag
        id: get_version
        run: |
          # Remove 'v' prefix if present (e.g., v1.2.3 -> 1.2.3)
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Update package.json version
        run: |
          npm version ${{ steps.get_version.outputs.version }} --no-git-tag-version
          echo "Updated package.json to version ${{ steps.get_version.outputs.version }}"

      - name: Build
        run: |
          npm run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public

      - name: Prepare release archive
        run: |
          # Create a directory with version name
          mkdir -p pieces-os-client-sdk-${{ github.ref_name }}
          
          # Copy files into it
          cp -r dist pieces-os-client-sdk-${{ github.ref_name }}/
          cp package.json package-lock.json pieces-os-client-sdk-${{ github.ref_name }}/
          
          # Copy README and LICENSE if they exist
          [ -f README.md ] && cp README.md pieces-os-client-sdk-${{ github.ref_name }}/
          [ -f LICENSE ] && cp LICENSE pieces-os-client-sdk-${{ github.ref_name }}/
          
          # Create archives
          zip -r pieces-os-client-sdk-${{ github.ref_name }}.zip pieces-os-client-sdk-${{ github.ref_name }}
          tar -czf pieces-os-client-sdk-${{ github.ref_name }}.tar.gz pieces-os-client-sdk-${{ github.ref_name }}
          
          # Cleanup
          rm -rf pieces-os-client-sdk-${{ github.ref_name }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            pieces-os-client-sdk-*.zip
            pieces-os-client-sdk-*.tar.gz 
