/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * This is a Semantic Version Enum that will reflect the Semantic version of the api.
 * @export
 * @enum {string}
 */
export declare enum EmbeddedModelSchemaSemanticVersionEnum {
    Major0Minor0Patch1 = "MAJOR_0_MINOR_0_PATCH_1"
}
export declare function EmbeddedModelSchemaSemanticVersionEnumFromJSON(json: any): EmbeddedModelSchemaSemanticVersionEnum;
export declare function EmbeddedModelSchemaSemanticVersionEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddedModelSchemaSemanticVersionEnum;
export declare function EmbeddedModelSchemaSemanticVersionEnumToJSON(value?: EmbeddedModelSchemaSemanticVersionEnum | null): any;
