/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmbeddedModelSchema, ImageAnalysis } from './';
/**
 *
 * @export
 * @interface ImageAnalyses
 */
export interface ImageAnalyses {
    /**
     *
     * @type {EmbeddedModelSchema}
     * @memberof ImageAnalyses
     */
    schema?: EmbeddedModelSchema;
    /**
     *
     * @type {Array<ImageAnalysis>}
     * @memberof ImageAnalyses
     */
    iterable: Array<ImageAnalysis>;
}
export declare function ImageAnalysesFromJSON(json: any): ImageAnalyses;
export declare function ImageAnalysesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageAnalyses;
export declare function ImageAnalysesToJSON(value?: ImageAnalyses | null): any;
