"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LanguageClassifierPriorReturnableToJSON = exports.LanguageClassifierPriorReturnableFromJSONTyped = exports.LanguageClassifierPriorReturnableFromJSON = void 0;
function LanguageClassifierPriorReturnableFromJSON(json) {
    return LanguageClassifierPriorReturnableFromJSONTyped(json, false);
}
exports.LanguageClassifierPriorReturnableFromJSON = LanguageClassifierPriorReturnableFromJSON;
function LanguageClassifierPriorReturnableFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'top5SortedDesc': json['top5SortedDesc'],
        'top5Colours': json['top5Colours'],
        'prediction': json['prediction'],
        'duration': json['duration'],
    };
}
exports.LanguageClassifierPriorReturnableFromJSONTyped = LanguageClassifierPriorReturnableFromJSONTyped;
function LanguageClassifierPriorReturnableToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'top5SortedDesc': value.top5SortedDesc,
        'top5Colours': value.top5Colours,
        'prediction': value.prediction,
        'duration': value.duration,
    };
}
exports.LanguageClassifierPriorReturnableToJSON = LanguageClassifierPriorReturnableToJSON;
